### ISSUE TITLE
API gateway timing out on spreadsheet upload

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#308]
# Describe the bug 

The upload of a spreadsheet by IRCC triggered a 502 error on the API gateway, s it seems that the API it taking too long to process the request.

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major - This impedes user experience, indicates a potential failure upon spreadsheet upload and leads to confusion. The notifications to be sent are successful, hence this is not a critical issue.

## To Reproduce

1. Upload a CSV spreadsheet containing 50K notifications, using simulator addresses is sufficient to trigger this.
1. Click the *Send All* button!
1. Get the timeout error.

# Expected behavior

No errors

# Impact

We get repeated 502 errors on these spreadsheet uploads. This can involve the support team to answer on warning or critical alerts. 

# QA
- [ ] upload csvs of various sizes (up to 50K) - the "send all now" button should quickly return and not cause a timeout

# Screenshots

No screenshot available for now. The whole page said to retry the operation later, hence the error is not even properly surfaced as the website is blanking.

# Additional context

This error was seen repeatedly during the mass send of 1M emails over 2 days by one of our user.
The [service](https://notification.canada.ca/services/8cc00648-0b2e-474e-a5a5-9da3c72b2560) and [template](https://notification.canada.ca/services/8cc00648-0b2e-474e-a5a5-9da3c72b2560/templates/f61468c0-609a-4c00-9d4f-14c42242bc5b) involved.

**Comment by sastels** [comment]
Looking at the csv's IRCC used, they actually had an extra named column that wasn't in the template. I verified with a small send that this all works (ie the proper columns are used to construct the notification. In this case, they have a `Date` column that isn't used in the template:
```
email address,Date,Date_EN,Date_FR,Date_Spanish
success@simulator.amazonses.com,2021-12-10,"December 10, 2021",10 décembre 2021,10 de diciembre de 2021
success@simulator.amazonses.com,2021-12-11,"December 11, 2021",11 décembre 2021,11 de diciembre de 2021
```

**Comment by sastels** [comment]
recreated [template on staging](https://staging.notification.cdssandbox.xyz/services/3ae2fb6a-bec7-47d6-8f8b-36e2519f7c6d/templates/4560acb6-557d-42f2-a010-9a9662671a2b).

Send 50K row file. upload was fine:
[Uploading... image.png]

**Comment by sastels** [comment]
Add some logging to help figure out in staging:
https://github.com/cds-snc/notification-api/pull/2130

**Comment by sastels** [comment]
In Athena with the query
```
select time, cast(elb_status_code as integer) as code, request_url, target_processing_time as api_lambda_time
from alb_logs
where request_url like '%start-job%'
order by target_processing_time desc
limit 100
```
We can see the IRCC requests timing out after 29 seconds, but all other recent jobs have taken less than 19 seconds. Don't know how big those jobs were though.

**Comment by sastels** [comment]
Logging is in staging! Running the big send again we see from [this query](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-1800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20message*2c*20*40logStream*0a*7c*20filter*20message*20like*20*2fTEMP*20LOGGING*2f*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2020*0a~queryId~'d53bda38-3ddb-4cd5-8593-ed59697a8f43~source~(~'*2faws*2flambda*2fapi-lambda))):
<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0cyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5157e92defd74b641f723d25630922538eb53040/image.png" alt="image.png" />

So checking that the service will not go over its limit is taking about a minute!

Since we are sending emails, [this is the code that is taking a minute to run](https://github.com/cds-snc/notification-api/blob/6f4903dd9f03aabca626df05ce79c4771b8b7f5f/app/job/rest.py#L191-L196):
```
   elif template.template_type == EMAIL_TYPE:
        check_email_daily_limit(service, len(list(recipient_csv.get_rows())))
        scheduled_for = datetime.fromisoformat(data.get("scheduled_for")) if data.get("scheduled_for") else None

        if scheduled_for is None or not scheduled_for.date() > datetime.today().date():
            increment_email_daily_count_send_warnings_if_needed(service, len(list(recipient_csv.get_rows())))
```

There are three things here that could be the issue:
- `recipient_csv.get_rows()` might take a while, and we are calling it twice to get the length of the file. There might be a better way.
- `check_email_daily_limit()`
- `increment_email_daily_count_send_warnings_if_needed()`

**Comment by sastels** [comment]
With a bit more logging we get
 <img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2E3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a02f260695ec040c757bfbdeb928af0734cb9393/image.png" alt="image.png" />

So it's taking half the time now. I believe what is happening is that `recipient_csv.get_rows()` is taking 30 seconds to run. Before we were calling it twice, but in the recent [logging PR](https://github.com/cds-snc/notification-api/pull/2132/files) we used properties of `recipient_csv` that cache the results, so now it's only being caused once.

**Comment by sastels** [comment]
Can get the notification count from the s3 object's metadata instead. preparing a PR...

**Comment by sastels** [comment]
This should fix it!
https://github.com/cds-snc/notification-api/pull/2133

**Comment by sastels** [comment]
This should fix it!
https://github.com/cds-snc/notification-api/pull/2135

**Comment by sastels** [comment]
testing on staging with the big IRCC file now takes about one second with no timeouts.

**Comment by jimleroyer** [comment]
I will QA this morning.

**Comment by sastels** [comment]
Jimmy will QA for sure this time!

**Comment by jimleroyer** [comment]
Tested and working with the same template that IRCC used and with a 50K entries spreadsheet. The upload took a few seconds (~5s) but there were no timing out. The period of time after clicking *Send all* was almost instantaneous. This can be considered fixed and working.
